spring:
  application:
    name: native-demo  
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      # native build fails to serialize without it  
      fail-on-empty-beans: true
    default-property-inclusion: non-null
  security:
    user:
      name: user
      password: secret
      roles: app

logbook:
  filter:
    enabled: true
  predicate:
    exclude:
      0:
        path: /ping

logging:
  level:
    '[org.zalando.logbook]': WARN
    '[org.springframework.web]': DEBUG
  structured:
    format:
      console: logstash


jwt:
  private.key: classpath:rsa/app.key
  public.key: classpath:rsa/app.pub	